
import "./globals.css";
import Navigation from "./components/navigation";
import { Container } from "@mui/material";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <header>
           <Navigation />
       </header>
       <main>
        <Container sx={{my:3}}>{children}</Container>
       </main>
      
      </body>
    </html>
  );
}
