
import "./globals.css";
import Navigation from "./components/navigation";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <header>
           <Navigation />
       </header>
       <main>
        {children}
       </main>
       <footer>
           Footer
       </footer>
      </body>
    </html>
  );
}
